# Generated by Django 4.2.1 on 2023-06-08 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.CharField(editable=False, max_length=20, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('billing_address_line_1', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('city', models.CharField(choices=[('Tehran', 'Tehran'), ('Karaj', 'Karaj'), ('Fardis', 'Fardis')], max_length=50)),
                ('postal_code', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('checked', 'Checked'), ('delivered', 'Delivered'), ('received', 'Received')], default='pending', max_length=20)),
                ('is_paid', models.BooleanField(default=False, null=True)),
                ('telephone_number', models.CharField(max_length=20, null=True)),
                ('total', models.CharField(default='0 ریال', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
