# Generated by Django 4.2.1 on 2023-06-11 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='billing_address_line_1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(choices=[('Tehran', 'Tehran'), ('Karaj', 'Karaj'), ('Fardis', 'Fardis')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
